name: Docker build and push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.12
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: docker build
      run: |
        docker build -t lasse1990/hello_world_test:0.0.1 .
    - name: docker push
      run: |
        docker push lasse1990/hello_world_test:0.0.1
